### ISSUE TITLE
Feature Request: Hide scrollbar

### ISSUE THREAD

**Issue by dboune** [mrcoles/full-page-screen-capture-chrome-extension#61]
Hiding the scrollbar would be a nice additional touch. For now I apply the following rule manually.

```css
::-webkit-scrollbar { width: 0 !important }
```
